### ISSUE TITLE
icons - childline 'i'

### ISSUE THREAD

**Issue by SavageWilliam** [childline-yoti/online-content-reporter#111]
@lizziesumner As requested please add files for the childline 'i' icon here 😄 

@denesnori https://www.materialui.co/icons use as placeholder until

**Comment by denesnori** [comment]
@lizziesumner  Please send us the icons, then we can finalize the changes based on your suggestions, and send new screenshots :)

**Comment by lizziesumner** [comment]
Hi-  we are trying to source the icon, but both our designers are currently out of the office and we don't have access to their files.  Worst case, we'll have to use the non-brand one!

Thanks

Lizzie

**Comment by lizziesumner** [comment]
We found it!
![childline_icons_rgb_info advice copy](https://cloud.githubusercontent.com/assets/25616795/23945817/e5eb2aac-096f-11e7-9b1f-72843dd9ab48.jpg)

**Comment by denesnori** [comment]
Great! It's a .jpg so we can't change its color. I"ll get back to you if that causes any problems. 
(we can change colours of .svg files)

**Comment by lizziesumner** [comment]
I can resave it as PSD or EPS, but GitHub won't let me upload those file types

**Comment by denesnori** [comment]
Sorry, I missed your response yesterday. I'll play with it tomorrow and see what I can do.
