### ISSUE TITLE
Landing page content

### ISSUE THREAD

**Issue by SavageWilliam** [childline-yoti/online-content-reporter#116]
@lizziesumner @jenlittle 

Looking at the new content spreadsheet. I have some questions with Landing page.

I'm concerned that the new content on the landing page isn't as clear in describing the app. (This might be a by-product of previously planning in integrating this within the Childline website?)

I think we should design our app assuming it could be navigated to from anywhere. (A link from a friend, councillor, google search etc..).

Particularly the action button: 

'Yes I am under 18'   --> 'Report Content'

Just to show you how it currently looks..

![image](https://cloud.githubusercontent.com/assets/15717822/23901918/e6737b26-08c7-11e7-9f18-e442f5359c59.png)

![image](https://cloud.githubusercontent.com/assets/15717822/23901906/dd5ad066-08c7-11e7-9edc-af1cc62c9bab.png)

**Comment by lizziesumner** [comment]
Hi @SavageWilliam 

I can see your point, and I think I can make a few copy changes to make it a little clearer. I'll update the Google Sheet now and highlight the areas I've changed.

Lizzie

1.

**Comment by SavageWilliam** [comment]
Thanks! 👍

**Comment by SavageWilliam** [comment]
@lizziesumner 
Between receiving the new content and after receiving feedback that we should try and make clear that IWF will be handling the report... I've hacked out a 'How it works' content box (page 2 as above). Not sure if this is something you feel is useful/necessary?

**Comment by lizziesumner** [comment]
The content on the final step makes it clear that the IWF are handling the reports, e.g:

_"We've sent your report to the Internet Watch Foundation (IWF) who will review your request.

Your report may take a little while to complete. If you'd like to know when the IWF have looked at your report, enter your email address below. 

[Enter your email]

If you're worried about anything, Childline is always here for you. Call us for free on 0800 1111 or speak to us online."_

Hopefully that is clear enough for now.

Lizzie

**Comment by SavageWilliam** [comment]
Awesome, let me know when the spreadsheet for the landing page has been updated

**Comment by lizziesumner** [comment]
Copy has been updated
