### ISSUE TITLE
Add email option

### ISSUE THREAD

**Issue by SavageWilliam** [childline-yoti/online-content-reporter#117]
Currently we display a thank you message explaining the content has been submitted. With the option of adding an email address:
- I guess we need to account for both cases (user adds email, or user doesn't add email)
- So we need a solution for how and when we actually send the data off... 

Options I can see which solve this:
1) We make it explicit that the form isn't completed until the final button after the option to add email. Keeping it clear that adding an email is optional.

2) We Send the form off in 'step 2 of 2' with submit. And then a user decides to add their email, we can send off the same form again with that email address added to it.

I hope that makes sense?

**Comment by lizziesumner** [comment]
My preference would be option 2 - form is send on submit and the email entry is just an optional extra. We would need to make that clear in the copy on that screen.

**Comment by SavageWilliam** [comment]
Alright, well it currently is set up that way in terms of content and design.

We'll have to send off two separate reports to IWF on addition of email address. As we have to account for those that don't add their email and send off an email at that point.

Unless we can build a system that hangs to see if their email address is added, and if not it'll fire the IWF email when the app closes.
