### ISSUE TITLE
If no criteria is selected on Step 1

### ISSUE THREAD

**Issue by SavageWilliam** [childline-yoti/online-content-reporter#118]
We discussed during the prototype that we'd want to block the user from the second form IF the content doesn't match any of the criteria.

Do we still want to do this? We can do a number of things if 'Next' is selected without clicking any of the criteria:

1) Have some text (maybe red) appear just under the form (like a password error), saying something like 'the content must meet at least 1 of the above criteria'

2) Have a modal pop up explaining a similar thing

3) We could allow the user to then ignore the warning and still proceed/or we can simply block access to the next form unless at least 1 is clicked?

**Comment by denesnori** [comment]
Hi @lizziesumner  and @jenlittle,

I would like to start working on this feauture. Please give us a  feedback, whether you prefer option 1,2, or 3.

Thanks!
Nóri

**Comment by lizziesumner** [comment]
Hi

Option 1 sounds like the simplest to implement and is inline with standard form error messaging, providing it is clearly displayed on the form.

We would not want to let the user proceed unless one option is selected, so the button should not be active until at least one box is ticket

**Comment by denesnori** [comment]
Great! Thanks @lizziesumner
