### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by denesnori** [childline-yoti/online-content-reporter#130]
Hi @lizziesumner  and @jenlittle,
Can you give us some feedback based on the current screenshots? 

- One thing I noticed while I was making the screenshots is that we should increase the font-size at some places... 
- The other thing we are aware of is that we still have to add icons to some buttons and fields.
- Ooops...And I just realized that the warning message for the url and the image criteria is not a correct sentence..

Mobile view:
Home_1
![homepage_1](https://cloud.githubusercontent.com/assets/18500240/23973288/61ab9890-09cd-11e7-9310-a3b93dff2250.png)
Age_check_upper
![page_1_part1](https://cloud.githubusercontent.com/assets/18500240/23973289/64c61316-09cd-11e7-8f19-47873d19754c.png)
Age_check_lower
![page_1_part2](https://cloud.githubusercontent.com/assets/18500240/23973292/6634c8c8-09cd-11e7-834b-b5d329e88c6b.png)
Age_check_with_QR
![page_1_part3](https://cloud.githubusercontent.com/assets/18500240/23973296/67aa48d6-09cd-11e7-91a9-aece9ae5fe85.png)
img criteria upper
![img_criteria_part1](https://cloud.githubusercontent.com/assets/18500240/23973303/750e4450-09cd-11e7-91da-af691e68ac5d.png)
img criteria lower
![img_criteria_part2](https://cloud.githubusercontent.com/assets/18500240/23973306/7695ab2e-09cd-11e7-84cb-91119751a231.png)
img criteria required
![img_criteria_part3](https://cloud.githubusercontent.com/assets/18500240/23973309/786fe572-09cd-11e7-8a4c-d18e0c8f5d38.png)
url form upper
![url_form_part1](https://cloud.githubusercontent.com/assets/18500240/23973312/7b5d3c80-09cd-11e7-8a6c-05771a2f0b38.png)
url form lower
![url_form_part2](https://cloud.githubusercontent.com/assets/18500240/23973317/808f0774-09cd-11e7-9c72-1fbf1246eae1.png)
submit
![modal](https://cloud.githubusercontent.com/assets/18500240/23973656/074baba4-09cf-11e7-8956-8ef31e923e08.png)

overage
![overage](https://cloud.githubusercontent.com/assets/18500240/23973322/8551e7ea-09cd-11e7-9e3d-7c4882be6fc8.png)

Desktop view:
home
![desktop_home](https://cloud.githubusercontent.com/assets/18500240/23973384/dd1eaf30-09cd-11e7-9189-1f9009c58921.png)
age check upper
![desktop_agecheck_1](https://cloud.githubusercontent.com/assets/18500240/23973387/def12a9a-09cd-11e7-8977-423d9165d0ac.png)
age check lower with qr
![desktop_agecheck_2](https://cloud.githubusercontent.com/assets/18500240/23973389/e1475d50-09cd-11e7-938a-0826e7c72645.png)
img criteria upper
![desktop_img_criteria_1](https://cloud.githubusercontent.com/assets/18500240/23973392/e40402a0-09cd-11e7-9315-1b9256da4c5f.png)
url form 
![desktop_url_form_1](https://cloud.githubusercontent.com/assets/18500240/23973398/ed9004c2-09cd-11e7-97fc-09d03df6ce72.png)
url form required
![desktop_url_form_2](https://cloud.githubusercontent.com/assets/18500240/23973405/f0b6aa02-09cd-11e7-8d0c-2ba2bae7f780.png)
submit
![desktop_modal](https://cloud.githubusercontent.com/assets/18500240/23973653/fe219f52-09ce-11e7-9cba-25c670a8b1ba.png)

overage
![desktop_overage](https://cloud.githubusercontent.com/assets/18500240/23973410/f3972a62-09cd-11e7-894c-d30d6048311e.png)

**Comment by lizziesumner** [comment]
Hi @denesnori 

Thanks for sharing, these look great.  A couple of things I've noticed are:

1) The Childline logo is not our official brand asset. I'll find one and send it over
2) Any instance of the sentence "What can I do if I'm over 17?" needs to be changed to "What can I do if I'm over 18?" 
3) The copy on the 'criteria selection screen' is not correct. Please can it be changed to:

_Remove title: Why are you reporting?
Please tell us more about the image or video. Does the image contain one or more of the following:_

4) On the criteria selection screen the red error message copy needs to change to: "You can't proceed without ticking at least one option."

5) On the over 18 journey, the copy needs to be updated to match the supplied copy
6) On the over 18 journey, any mention of CEOP needs to be removed as this is no longer a contact option.

Thanks

Lizzie

**Comment by denesnori** [comment]
in progress
- [ ] 1
- [x] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6

**Comment by lizziesumner** [comment]
Hi

Sorry, just spotted another minor change.  On each page the top banner currently reads 'Report concern with online content' - this needs to be changed to "Report an image or video" (as per the landing page title.  Sorry, but the service didn't think that kids would know what 'content' meant!

Thanks
