### ISSUE TITLE
404 page question

### ISSUE THREAD

**Issue by denesnori** [childline-yoti/online-content-reporter#138]
Hi @lizziesumner ,

Do you have any ideas how you imagine the '404 Not Found page'?
This is how it look like on the Childline site:

I imagine it like:
- Report concern with online content banner
- message similar or exactly the same same as on the childline site + funny image
- footer
Can we use the snake image from the childline site?
![404](https://cloud.githubusercontent.com/assets/18500240/24007371/413d01ae-0a66-11e7-8511-80f879f95ae9.png)

**Comment by lizziesumner** [comment]
Hi @denesnori 

Just to check, where would this 404 appear - would it be on the Childline site, or a screen within the app?

As we don't want the app to be overly Childline branded, I think we'd want to avoid using the same 404 we currently have on the site. A toned down version of this would be fine. The messaging can be the same, but maybe add in a additional link to chat to a counsellor as a sign post e.g.

**Sorry, we can't find this page**

You might have clicked on an old or broken link.

Try searching our site or following the links around this page to find what you're looking for. If you need to talk to someone, you can call 0800 1111 or [talk to a counsellor now](https://childline.org.uk/get-support/1-2-1-counsellor-chat/).

**Comment by SavageWilliam** [comment]
The 404 would appear on a screen within the app. The app is technically disconnected with the childline website. 

Currently looks like this: 
![image](https://cloud.githubusercontent.com/assets/15717822/24082615/4d8ceed4-0cd1-11e7-86c2-6e0cca7141f2.png)

Let us know the changes you'd like to make

**Comment by lizziesumner** [comment]
Hi @SavageWilliam 

Thanks for confirming - this looks great, thanks.

Lizzie
