### ISSUE TITLE
week 4 todos

### ISSUE THREAD

**Issue by denesnori** [childline-yoti/online-content-reporter#140]
From previous week:
- [x]  Host our server on a secure network? http? we have cert and pem in keys already? **DONE**

Small fixes:
- [ ] discuss whether we need material launch iconon every button...
- [x] officical childline logo (ask @lizziesumner ) to send it
- [x] childline info svg/icon (we have the .jpg version..but we can't change colours)
- [x] 404 page layout

Discuss/implement
- [x] #90  Redux saga
- [x] #85 Socket io in internet explorer
- [x] #59 REFRESH **PRIORITY1**
- [x] #53
- [x] #139 **DONE**

- [x] deploy the app to heroku 
- [x] and fix the fonts on the deployed version
- [x] if you go back to previous form keep the checked boxes checked! (I merged your branch, but it broke everything, so I wrote my own version. Hope you don't mind) **DONE**
- [x] setup code coverage .display badges on repo

**Comment by SavageWilliam** [comment]
Been havign heroku issues with the new version. found out why...

![image](https://cloud.githubusercontent.com/assets/15717822/24079767/bf15a41c-0c98-11e7-81a1-a273797a9d30.png)

..my bad for thinkign we needed to make it secure ourselves. Heroku does thius!

**Comment by SavageWilliam** [comment]
yup -  confirmed. We need to generate a http server our end. Sorry to make you do that work!

**Comment by lizziesumner** [comment]
HI

As promised, please find attached the Childline logo file

Lizzie
![childline primary logo_for print_blue](https://cloud.githubusercontent.com/assets/25616795/24097427/a52795a4-0d5d-11e7-8fb4-52d3a64ec711.jpg)

**Comment by denesnori** [comment]
Thanks @lizziesumner , I updated the footer with img you sent me. It looked dodgy,  since the footer has a greyish background and the image you sent has a white background, and we can't change the background of jpg-s.

I would suggest either giving a white background to the footer, or keeping the old version.

**Comment by lizziesumner** [comment]
Hi - Apologies, I tried to source a file with a transparent background, but our designers are not around to provide it.  In this instance, we should stick to the original even though if off brand

Thanks

Lizzie

**Comment by denesnori** [comment]
Thanks @lizziesumner , We really appreaciate your help :)
