### ISSUE TITLE
Please change max age back to 18

### ISSUE THREAD

**Issue by Annadepulford** [childline-yoti/online-content-reporter#173]
@SavageWilliam @denesnori please could you change the max age on the app back to 18 ASAP? I was hoping to make the change, but don't have publishing access. NSPCC are waiting for this change to carry out user testing, so it is very urgent.

**Comment by SavageWilliam** [comment]
@Annadepulford Absolutely,

I'll do this over my lunch break today

**Comment by sofer** [comment]
@SavageWilliam let us know when it's done.

**Comment by SavageWilliam** [comment]
https://content-reporter.herokuapp.com/ 

- Under 18 version.

@sofer @Annadepulford @lizziesumner @jenlittle @denesnori 

- let me know if there are any issues with it! I don't have any under 18 year olds around the test.

**Comment by jenlittle** [comment]
Thank you Will [😊]

________________________________

**Comment by Annadepulford** [comment]
Thanks, Will!
