### ISSUE TITLE
refresh / server requests (react-router)

### ISSUE THREAD

**Issue by SavageWilliam** [childline-yoti/online-content-reporter#59]
On refresh the app makes a new get request to our SERVER

React-router issue

Possibly we need to sync the browser history or something? Or maybe disable the browser default refresh process to stop it firing a new GEt request.

**Comment by denesnori** [comment]
Making it an isomorphic app should solve this, I think.
(typeof ISOMORPHIC_WEBPACK === 'undefined') based on this we can do either server side or browser side rendering

Although, I don't exactly know how to implement it...

**Comment by denesnori** [comment]
this is the best explanation about this problem that I've found so far

http://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writting-manually

**Comment by SavageWilliam** [comment]
Did you read the resource you linked, also found that but hard to find what we need to extract thats applicable for us
