### ISSUE TITLE
add functions to save url, and url description

### ISSUE THREAD

**Issue by denesnori** [childline-yoti/online-content-reporter#68]

**Comment by SavageWilliam** [comment]
I can start building this now ? :)

**Comment by SavageWilliam** [comment]
https://github.com/chromakode/react-html-email 

for emailing the data?

**Comment by SavageWilliam** [comment]
research how to send the email - mailchimp?

**Comment by SavageWilliam** [comment]
http://stackoverflow.com/questions/29791721/how-get-data-from-material-ui-textfield-dropdownmenu-components
