### ISSUE TITLE
To dos end of week2... Nori friday (wills week is sunday-thursday in israel)

### ISSUE THREAD

**Issue by SavageWilliam** [childline-yoti/online-content-reporter#81]
- Add url to modal
- tests for redux and yoti functions
- final touches on css to match prototype
- contact PO's and ask to test - https://childline-report-image.herokuapp.com/
- Work out how to email a email address with nice HTML format with the data we provide. --DONE (not yet formatted)

- Fix state save of content type. (currently doesnt toggle when you click a checkbox.. it just adds another!! we need the state to toggle :))--DONE

**Comment by denesnori** [comment]
As of Saturday night:
-due to illness I worked on Saturday instead of Friday

- setup email notifications: image Description, url, and url description are sent to childline.report.content@gmail.com now. 
- I fixed the addImageDescription function for the checkBoxes

**Comment by denesnori** [comment]
- [ ] Form tests
- [ ] Yoti tests
I can't figure out how to test them..IT would be nice if you tried to solve this on Sunday
