### ISSUE TITLE
socket.io

### ISSUE THREAD

**Issue by SavageWilliam** [childline-yoti/online-content-reporter#85]

**Comment by denesnori** [comment]
http://stackoverflow.com/questions/12993704/ie-and-socket-io-compatibility

http://stackoverflow.com/questions/38135161/is-it-possible-to-using-socket-io-client-under-ie-9

**Comment by denesnori** [comment]
I added this to our code...it is supposed to solve it...but i couldn't test it
```
 socket.set('transports', [
     'websocket'
   , 'flashsocket'
   , 'htmlfile'
   , 'xhr-polling'
   , 'jsonp-polling'
 ]);
```

**Comment by denesnori** [comment]
I couldn't install internet explorer on ubuntu...i got all different kind of error messages...can you test whether it works on IE now?

**Comment by SavageWilliam** [comment]
will do
![image](https://cloud.githubusercontent.com/assets/15717822/24080122/0a22f380-0ca1-11e7-8520-e602475af323.png)

found an ie a simulator... websocket seems fine, but its the favicon that crashes..
