### ISSUE TITLE
week 3 initial list of todos

### ISSUE THREAD

**Issue by SavageWilliam** [childline-yoti/online-content-reporter#92]
- [x] USER testing
- [x] add back button to url/description form view
- [x]  allow broswer 'back' button to take you to prev page on ALL routes
- [x] add logic to display message that cannot process to url form if imageCriteria doesnt have any toggled
- [x] deal with entering email address to be notified (send off return address also)
- [x] Decide upon styling of anchor tags (links) and add on hover color change
__underline when on hover.. (like childline website) and bold text (instead of different colour)__
- [x] smoothen yoti flow by preloading QR code

- [x] use max-width: 800px margin: 0 auto; for media queries larger than 1000px or something

- [ ] Host our server on a secure network? http? we have cert and pem in keys already?

**Comment by denesnori** [comment]
- [ ] Yoti verification is broken
