### ISSUE TITLE
User testing 

### ISSUE THREAD

**Issue by SavageWilliam** [childline-yoti/online-content-reporter#94]
@jenlittle @lizziesumner 

Hey guys, I hope all is well over at NSPCC.

Just wanted to say: the site [here](https://childline-report-image.herokuapp.com/) Is functioning on both mobile and desktop. Would be great to get some User Testing results on this. Apologies for the previous Bug, there were complications in switching it over to the childline-email we created in terms of appId, keys and things.

Anyway, coming into our third week we really need to get some user testing on the product so we can iterate and improve on it!

 "Agile workflow"

**Comment by lizziesumner** [comment]
Hi @SavageWilliam and @denesnori 

The good news is we've done some testing at our end and hope to get about 5 young people testing it this week.

Both our designers and our content team have reviewed it and made some suggestions, which has been really helpful.

**Designs** - our designer Eric has mocked up the app so it's more in-keeping with the look and feel of the Childline site. We wanted to make it clear that this is not a 100% Childline owned tool, so we've toned down some of the colours and kept the IWF logo prominent. I've attached his designs. Please not, our content team are working on the copy (the copy used in these mock ups is not final). He also didn't have a chance to mock up the over 18 screen.

![00 widget](https://cloud.githubusercontent.com/assets/25616795/23853037/abce862c-07e2-11e7-8963-4e1ea9e70396.png)
![01 verify age](https://cloud.githubusercontent.com/assets/25616795/23853040/abd34d74-07e2-11e7-86b9-f948b91a94f5.png)
![02 step 1](https://cloud.githubusercontent.com/assets/25616795/23853038/abcf5872-07e2-11e7-963c-3796e280596f.png)
![03 step 2](https://cloud.githubusercontent.com/assets/25616795/23853036/abce5fd0-07e2-11e7-9730-b9e8ffc17ac2.png)
![04 complete](https://cloud.githubusercontent.com/assets/25616795/23853039/abcfd2fc-07e2-11e7-9e6f-64b51f630f58.png)


**Copy** - We should have reworked copy by the end of today. By talking through the app with them, we found that some areas (such as the request for users to go away and create a Yoti account) needs to be clearer, so there may be some suggestions about how we can achieve that shortly.

**Feedback** - We'll collate the feedback we've received so far and get this over to you. So far, it's been pretty positive and it works really smoothly now the bug has been resolved.

**Response from IWF** - The IWF finally got back to us with some answers to our questions. Do you want to start a new thread for this? I can copy and paste their responses.

Lizzie

**Comment by denesnori** [comment]
Thanks @lizziesumner.
Please open a new thread and copy&paste NSPCC's response.

**Comment by SavageWilliam** [comment]
@lizziesumner would we be able to get the little 

'information' / i icon? It looks like a childline custom one. Used on 'why are you reporting page' in the yellow container

**Comment by lizziesumner** [comment]
@SavageWilliam I've requested this from our designers, will send it over when it arrives.

**Comment by SavageWilliam** [comment]
@lizziesumner  Awesome, thanks.

1) I've created the 'footer' which appears on every page.

Its great that you have included one mobile view of the app (the landing page). Whilst I think the design looks great when on mobile.. I think on desktop there could be an overwhelming amount of the blue? (all of the screen minus the footer). 

Heres what I currently have for the landing page (desktop), what do you think? 
![image](https://cloud.githubusercontent.com/assets/15717822/23858336/bf624dd8-0808-11e7-901f-2a50208f061a.png)

Heres it on mobile:
![image](https://cloud.githubusercontent.com/assets/15717822/23858517/5856a430-0809-11e7-8149-6fad6c8aaad4.png)

###Questions
1) Theres a few tweeks needed (icon in button centered), but any comments on the difference in design.

2) Definitely want to remove the childline in the top left and phone number top right? Just wana clarify. Can happily do so.

**Comment by lizziesumner** [comment]
Hi @SavageWilliam - with the landing page mock up that our designer did, we're confident that will work well on desktop and mobile and don't think the blue is an issue due to the use of the white space and grey footer (unless I'm looking at the wrong screen!)

Regarding your questions: 

1. Ideally we'd like to stick to the designs our team have created - they are more in keeping with our site.

2. Yes, please can we remove the phone number and logo at the top - this app will always be situated within the Childline website which has these elements in it's header and footer.

3. The original idea was that it would be Childline branded, however after showing it to some of our counsellors and Childline team they were keen that it was clearly dual branded. We want to avoid young people thinking that Childline will be handling their requests, and make it clear that the IWF are removing the images (this will also be reflected in the amended copy). Therefore, our designer has restricted the colour palette to make it less Childline.  Hope that makes sense.

**Comment by SavageWilliam** [comment]
@lizziesumner Can you send the desktop design for the landing screen

**Comment by lizziesumner** [comment]
@SavageWilliam - the designer has not mocked up a mobile version of this.  The image attached is a block that would sit on our website (hence the smaller dimensions). From this, it would link through to the next step (the page with Yoti information).  

If that's not possible, the alternative you have mocked up is great, but I think it could benefit from some of the white spacing between the content and footer.

Thanks

Lizzie

![00 widget](https://cloud.githubusercontent.com/assets/25616795/23863921/f06e82de-0808-11e7-8cfb-dc7216ff24af.png)

**Comment by SavageWilliam** [comment]
We'll do our best to stick to the designs of the team... however a few points to bare in mind.

1) At this stage in the project, a design change as drastic as this will set us back and take a lot of time undoing things we've spent a whilst on.

2) Design changes at this stage should be based almost 90% on User testing. Whilst there seems to be very valid reasoning behind some of the decisions (colours schemes and content). It would be great to have some more justification from User testing for the some of the other changes. 

From this end, we've shown the current designs alongside the new designs (like the image below) and we're getting some mixed feedback. Particularly on use of space in the new designs and mixed use of bold/regular font.

https://cloud.githubusercontent.com/assets/15717822/23859178/761075b2-080b-11e7-9693-4e7b960ec0c5.png  

We also wondered about the final page. The new design seems to be more of anther page, rather than a modal? Whats the reasoning behind this?

@denesnori and I have prioritised changed to implement asap:

1) Scrapping the progress bar and using step 1 of 2 etc.
2) adding footer to all pages
3) Adjusting the styling of the 'call to action' buttons (aligning left etc.)

**Comment by SavageWilliam** [comment]
@lizziesumner  In terms of integrating the first page on your website.

This would be new to us, however we'll be happy to look into it! I imagine we'd have to cooperate with your web developers to make that happen? As they'd have to add it to your current code base. I think it uses 'iframe's.

**Comment by SavageWilliam** [comment]
Just want to clarify 'the alternative you have mocked up is great' - the screenshots are what currently exists with code 😄 , not mockups. 

I hope you understand why we'd love to hear some more rational behind the changes before implementing them.

**Comment by lizziesumner** [comment]
Hi 

Appreciate that these are large changes, however many are coming from our user feedback with staff and the Childline service. Several found the lack of clarity with the progress tracker to be confusing, which is why it has been stepped out as 1 & 2 steps. This helps set up the expectation. Other changes are to fit in with our brand guide - although they appear minor, it would cause issues with getting things signed off at the end.  Apologies, for referring to them as 'mock ups', it's force of habit - we are not used to working directly in code, normally designs are signed off before anything is built!

As far as I know, there is no reason why the final page has been treated like this. However, it does make it feel more like you have completed the form as you land on a separate page.

We're not sure what integration would be needed at this stage - at the moment the idea is to link from the content block to the form, but there has been no decision as to where this form would sit. It may be able to live on the Childline website, but we would need agreement from our editorial team so we could find it a suitable home on the site.

**Comment by SavageWilliam** [comment]
@lizziesumner No need to apologise 😄 . Just wanted to ensure you were aware that it was functioning code and not a static image. I suppose we haven't had any choice but to build the same designs as the prototype up until now. 

Also wanted to clarify we're using the same terms. 

Landing page I'm referring to here:
https://cloud.githubusercontent.com/assets/25616795/23863921/f06e82de-0808-11e7-8cfb-dc7216ff24af.png

That is the page that lacks the white space and would be good to see as desktop? 

And "link from the content block to the form", which element is the content block you're referring to? Would the form be our app as a whole?

Sorry for my confusion, it's been a long day 😄

**Comment by lizziesumner** [comment]
Hi @SavageWilliam 

Looks like we're talking about the same thing when we say landing page (i.e the first screen of the app).

Our designer has taken the landing page and turned it into a 'content block' or module that would appear on our website. 

In hindsight, I think this over complicates things and we'd be better off leaving the landing page as it is. Unfortunately our designer is now out of the office until the 5th April so we're not going to be able to get a desktop version.

For the purpose of moving forward, the version you have created looks great, providing the button can be left aligned.

Lizzie

**Comment by lizziesumner** [comment]
Hi

The new content is now ready. The changes have come from discussions with the service as well as user testing - we're hoping that the instructions are now a little clearer and informative.

Copy can be viewed here: https://docs.google.com/spreadsheets/d/18kYyhdCyXWtoK5DObVxOiXt7py4zNN6T2F-FYa5K6Bc/edit?usp=sharing

There is one tab for the under 18 journey and one for over 18s.

Thanks

Lizzie

**Comment by SavageWilliam** [comment]
@lizziesumner 

Brilliant, thanks for this - we've proceeded to implement the new designs and will amend the content. 

We'll plan to get these implemented by Friday morning and then hosted online! Hopefully you'll have time on Friday to prepare a final User Testing (on young people?) and roll it out over the weekend. This should enable us to respond to the feedback in our last week and iron out any final issues before handover and final deployment! 

### Question with step 6 of the 'under 18' user journey:

Currently we display a thank you message explaining the content has been submitted. With the option of adding an email address:
- I guess we need to account for both cases (user adds email, or user doesn't add email)
- So we need a solution for how and when we actually send the data off... 

Options I can see which solve this:
1) We make it explicit that the form isn't completed until the final button after the option to add email. Keeping it clear that adding an email is optional.

2) We Send the form off in 'step 2 of 2' with submit. And then a user decides to add their email, we can send off the same form again with that email address added to it.

**Comment by denesnori** [comment]
Hi @lizziesumner  and @jenlittle ,
Can we get some feedback about what would you like to see on the overage page?
At the moment it looks like: 
![overage_1403](https://cloud.githubusercontent.com/assets/18500240/23913830/06a45b40-08dc-11e7-82b7-b1625e63fafb.png)

**Comment by lizziesumner** [comment]
I can’t find the thread for this in GitHub – has it been moved?

**Comment by denesnori** [comment]
Hi @lizziesumner ,
I post it again :) It is the overage page at the moment.
![overage_1403](https://cloud.githubusercontent.com/assets/18500240/23944056/696a464e-0969-11e7-8ca0-22e178f8e42f.png)

**Comment by lizziesumner** [comment]
HI @denesnori 

This is looking great. In the updated copy you'll see that we've had to get rid of the link to CEOP as they cannot help adults, only children (but this is all reflected in the copy).

Would it be possible to reuse the external link icon, as we've done on other buttons? (the arrow in the box). We want to be clear that we are directing people off to a different site.

Thanks

Lizzie

**Comment by denesnori** [comment]
Yes, I'll do the fixes now :)
